import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { generatedFileHtmlComment, insertGeneratedHint } from "../skill/hint.ts";
import type { CliProgram } from "../types.ts";
import { docsTopicContent } from "./resolve.ts";

/** Relative output directory for `docs --save`. */
export const DOCS_SAVE_DIR = "docs";

/** Builtin docs topics generated by argsbarg (not consumer `docs.topics`). */
export const DOCS_GENERATED_SAVE_TOPICS = ["mcp", "api", "skill"] as const;

/** Whether `--save` should prepend a generated-file hint (argsbarg writers only). */
export function docsTopicIsGeneratedByArgsbarg(topic: string): boolean {
  return (DOCS_GENERATED_SAVE_TOPICS as readonly string[]).includes(topic);
}

/** HTML comment for generated markdown saved with `--save`. */
export function docsSaveGeneratedHint(program: CliProgram, topic: string): string {
  return generatedFileHtmlComment(`${program.key} docs ${topic} --save`);
}

/** Inserts save hint without breaking YAML frontmatter (`docs skill`). */
export function applySaveGeneratedHint(
  program: CliProgram,
  topic: string,
  content: string,
): string {
  if (!docsTopicIsGeneratedByArgsbarg(topic)) {
    return content;
  }
  const hint = docsSaveGeneratedHint(program, topic);
  return insertGeneratedHint(
    content,
    hint,
    topic === "skill" ? { afterFrontmatter: true } : undefined,
  );
}

/** File body for `--save` (hint on argsbarg-generated markdown only). */
export function docsTopicContentForSave(program: CliProgram, topic: string): string {
  return applySaveGeneratedHint(program, topic, docsTopicContent(program, topic));
}

/** Filename for a saved docs topic. */
export function docsSaveFilename(topic: string): string {
  if (topic === "schema") {
    return "schema.json";
  }
  return `${topic}.md`;
}

/** Relative path under cwd for a saved docs topic. */
export function docsSaveRelativePath(topic: string): string {
  return join(DOCS_SAVE_DIR, docsSaveFilename(topic));
}

/** Writes one docs topic under `./docs/`; returns relative path written. */
export function saveDocsTopic(program: CliProgram, topic: string): string {
  const dir = join(process.cwd(), DOCS_SAVE_DIR);
  mkdirSync(dir, { recursive: true });

  const rel = docsSaveRelativePath(topic);
  const abs = join(process.cwd(), rel);
  writeFileSync(abs, docsTopicContentForSave(program, topic), "utf8");
  return rel;
}
