import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { CliProgram } from "../types.ts";
import { docsTopicContent } from "./resolve.ts";

/** Relative output directory for `docs --save`. */
export const DOCS_SAVE_DIR = "docs";

/** Builtin docs topics generated by argsbarg (not consumer `docs.topics`). */
export const DOCS_GENERATED_SAVE_TOPICS = ["mcp", "api", "skill"] as const;

/** Whether `--save` should prepend a generated-file hint (argsbarg writers only). */
export function docsTopicIsGeneratedByArgsbarg(topic: string): boolean {
  return (DOCS_GENERATED_SAVE_TOPICS as readonly string[]).includes(topic);
}

/** HTML comment for generated markdown saved with `--save`. */
export function docsSaveGeneratedHint(program: CliProgram, topic: string): string {
  return `<!-- Generated by ${program.key} docs ${topic} --save; do not edit. -->\n\n`;
}

const SKILL_FRONTMATTER_RE = /^---\r?\n[\s\S]*?\r?\n---\r?\n/;

/** Inserts save hint without breaking YAML frontmatter (`docs skill`). */
export function applySaveGeneratedHint(program: CliProgram, topic: string, content: string): string {
  if (!docsTopicIsGeneratedByArgsbarg(topic)) {
    return content;
  }
  const hint = docsSaveGeneratedHint(program, topic);
  if (topic === "skill") {
    const match = content.match(SKILL_FRONTMATTER_RE);
    if (match) {
      return `${match[0]}${hint}${content.slice(match[0].length)}`;
    }
  }
  return `${hint}${content}`;
}

/** File body for `--save` (hint on argsbarg-generated markdown only). */
export function docsTopicContentForSave(program: CliProgram, topic: string): string {
  return applySaveGeneratedHint(program, topic, docsTopicContent(program, topic));
}

/** Filename for a saved docs topic. */
export function docsSaveFilename(topic: string): string {
  if (topic === "schema") {
    return "schema.json";
  }
  return `${topic}.md`;
}

/** Relative path under cwd for a saved docs topic. */
export function docsSaveRelativePath(topic: string): string {
  return join(DOCS_SAVE_DIR, docsSaveFilename(topic));
}

/** Writes one docs topic under `./docs/`; returns relative path written. */
export function saveDocsTopic(program: CliProgram, topic: string): string {
  const dir = join(process.cwd(), DOCS_SAVE_DIR);
  mkdirSync(dir, { recursive: true });

  const rel = docsSaveRelativePath(topic);
  const abs = join(process.cwd(), rel);
  writeFileSync(abs, docsTopicContentForSave(program, topic), "utf8");
  return rel;
}
