// Generated by dts-bundle-generator v9.5.1

/**
 * Values passed to a leaf command handler after parsing: app name, routed path, args, and merged options.
 */
export declare class CliContext {
	readonly appName: string;
	readonly commandPath: string[];
	readonly args: string[];
	readonly schema: CliCommand;
	readonly opts: Record<string, string>;
	readonly invocation: CliInvocation;
	/** Captures the merged program root, routed path, positional words, and option map for a leaf handler. */
	constructor(appName: string, commandPath: string[], args: string[], opts: Record<string, string>, schema: CliCommand, invocation?: CliInvocation);
	/** Returns whether a presence flag was set (including implicit "1" for boolean options). */
	hasFlag(name: string): boolean;
	/** Returns the string value for a string-valued option, if present. */
	stringOpt(name: string): string | undefined;
	/** Parses a stored string as a number; returns null if missing or not a strict double string. */
	numberOpt(name: string): number | null;
	/**
	 * Generic typed accessor: parses a stored string using the provided parse function.
	 * This is the TypeScript-native advantage over the Swift version.
	 */
	typedOpt<T>(name: string, parse: (s: string) => T): T | null;
	/** Returns the value(s) for a named positional slot. Varargs slots return string[]; single slots return string | undefined. */
	positional(name: string): string | string[] | undefined;
	private _posMap;
	private _positionalMap;
}
/**
 * How a leaf handler was dispatched.
 */
export type CliInvocation = "cli" | "mcp";
/**
 * Option kinds: presence (boolean flag), string (free-form text), number (strict double), or enum (fixed choices).
 */
export declare enum CliOptionKind {
	/** Boolean flag: no value token (may be implicit `"1"` when set). */
	Presence = "presence",
	/** Free-form string value. */
	String = "string",
	/** Strict floating-point value (parsed at validation time). */
	Number = "number",
	/** Fixed set of allowed string values. Requires non-empty `choices` on the option. */
	Enum = "enum"
}
/**
 * When `fallbackCommand` is used for missing or unknown subcommand tokens at a routing node.
 */
export declare enum CliFallbackMode {
	/**
	 * If argv has no next subcommand, route to `fallbackCommand`; if the token is unknown, error.
	 */
	MissingOnly = "missingOnly",
	/**
	 * If argv has no next subcommand or the token is not a known child, route to `fallbackCommand`.
	 */
	MissingOrUnknown = "missingOrUnknown",
	/**
	 * If the next token is present but not a known child, route to `fallbackCommand`.
	 * When the subcommand token is missing (exhausted argv), do not use fallback (implicit scoped help).
	 */
	UnknownOnly = "unknownOnly"
}
/**
 * A named flag or value option (`--long`, `-short`), listed on `CliCommand.options`.
 */
export interface CliOption {
	/** Option name (e.g., "name", "verbose"). */
	name: string;
	/** Description shown in help. */
	description: string;
	/** Option kind: presence flag, string value, or number value. */
	kind: CliOptionKind;
	/** Short option character (e.g., 'n' for -n). */
	shortName?: string;
	/** Whether this option must be provided. Cannot be used with Presence kind. */
	required?: boolean;
	/**
	 * Allowed values. Required when kind === Enum; ignored otherwise.
	 * Must be a non-empty array of distinct non-empty strings.
	 */
	choices?: string[];
}
/**
 * An ordered positional argument slot, listed on `CliCommand.positionals`.
 */
export interface CliPositional {
	/** Positional name (used in help and error messages). */
	name: string;
	/** Description shown in help. */
	description: string;
	/** Value kind for each consumed token. */
	kind: CliOptionKind;
	/**
	 * Minimum number of values required (default 1).
	 * Use `0` for an optional slot when paired with `argMax: 1`, or a varargs tail with `argMax: 0`.
	 */
	argMin?: number;
	/**
	 * Maximum number of values (`1` = a single required or optional word; default 1). Use `0` for an
	 * unbounded varargs tail (must be the last slot in the command’s `positionals` list).
	 */
	argMax?: number;
}
/**
 * Root-only. Enables `myapp mcp` and MCP stdio server metadata.
 */
export interface CliMcpServerConfig {
	/** `initialize` serverInfo.name (default: root `key`). */
	name?: string;
	/** `initialize` serverInfo.version (default: see resolveMcpVersion). */
	version?: string;
	/** Resource URI for schema export (default: `"argsbarg://schema"`). */
	schemaResourceUri?: string;
	/**
	 * Capture the user's login shell environment at MCP server start and merge it
	 * into process.env. Solves missing PATH, nvm/rbenv shims, Homebrew binaries,
	 * and shell exports that MCP hosts (e.g. Cursor) don't inherit.
	 */
	shellEnv?: boolean | string;
	/**
	 * Path to a .env file loaded into process.env at MCP server start, after shellEnv.
	 * Supports `~` expansion. Warns on stderr if the file does not exist.
	 * Always overwrites — envFile is authoritative for its keys.
	 */
	envFile?: string;
	/**
	 * Custom MCP resources exposed alongside the built-in argsbarg://schema resource.
	 * URIs must be unique and must not equal schemaResourceUri.
	 */
	resources?: CliMcpResource[];
}
/**
 * A custom MCP resource exposed under resources/list and resources/read.
 */
export interface CliMcpResource {
	/** Resource URI (must be unique; must not equal schemaResourceUri). */
	uri: string;
	/** Short display name for resources/list. */
	name: string;
	/** Optional human description for resources/list. */
	description?: string;
	/** MIME type (default: "text/plain"). */
	mimeType?: string;
	/** Called at resources/read time; must return the resource body. */
	load: () => string;
}
/**
 * Leaf-only. Controls how this command appears as an MCP tool.
 */
export interface CliMcpToolConfig {
	/** When `false`, omit from `tools/list` (default: exposed). */
	enabled?: boolean;
	/**
	 * Override the generated MCP tool description.
	 * Default: auto-generated from command path and description.
	 */
	description?: string;
	/**
	 * Environment variable names required at runtime.
	 * Appended to auto-generated MCP tool descriptions; enforced at tools/call time.
	 * Empty string counts as absent.
	 */
	requiresEnv?: string[];
}
/**
 * Base properties shared by all command nodes.
 */
export interface CliCommandBase {
	/** Program or command key (e.g., "myapp", "stat", "owner"). */
	key: string;
	/** Short description shown in help. */
	description: string;
	/** Additional notes shown in help (supports {app} placeholder). */
	notes?: string;
	/** Global or command-level flags/options. */
	options?: CliOption[];
	/** Root-only. When set, enables the `mcp` built-in subcommand. */
	mcpServer?: CliMcpServerConfig;
	/** Leaf-only. Per-tool MCP exposure and metadata. */
	mcpTool?: CliMcpToolConfig;
}
/**
 * A command node: either a routing group (has commands) or a leaf (has handler).
 *
 * The value passed to cliRun is the program root: name is the app/binary name.
 * The root may be a routing group or a leaf command.
 */
export type CliCommand = (CliCommandBase & {
	/** Handler function for leaf commands. */
	handler: CliHandler;
	/** Positional argument definitions. */
	positionals?: CliPositional[];
	/** Nested subcommands (empty for leaf commands). */
	commands?: never;
	/** Default subcommand (routing commands only). */
	fallbackCommand?: never;
	/** How fallbackCommand is applied at this routing node (routing commands only). */
	fallbackMode?: never;
}) | (CliCommandBase & {
	/** Nested subcommands. */
	commands: CliCommand[];
	/** Default subcommand when argv omits a command or uses an unknown token at this routing node. */
	fallbackCommand?: string;
	/** How fallbackCommand is applied at this routing node (not root-only). */
	fallbackMode?: CliFallbackMode;
	/** Handler function (leaf commands only). */
	handler?: never;
	/** Positional argument definitions (leaf commands only). */
	positionals?: never;
});
/**
 * Handler closure type for leaf commands.
 * Supports both sync and async handlers.
 */
export type CliHandler = (ctx: CliContext) => void | Promise<void>;
/**
 * Error thrown when the static CliCommand tree violates ArgsBarg rules.
 */
export declare class CliSchemaValidationError extends Error {
	/** Creates a schema validation error with a human-readable rule violation. */
	constructor(message: string);
}
/** Outcome of a non-exiting CLI invocation. */
export type CliInvokeKind = "ok" | "help" | "schema" | "error";
/** Result of cliInvoke: captured output and exit metadata without process.exit. */
export interface CliInvokeResult {
	/** Invocation outcome. */
	kind: CliInvokeKind;
	/** Simulated exit code. */
	exitCode: number;
	/** Captured stdout during handler execution. */
	stdout: string;
	/** Captured stderr during handler execution. */
	stderr: string;
	/** Set when kind === "error" (parse/validation message). */
	errorMsg?: string;
}
/**
 * Parses argv against the user root, runs the leaf handler, and returns captured output.
 * Never calls process.exit.
 */
export declare function cliInvoke(root: CliCommand, argv: string[]): Promise<CliInvokeResult>;
/**
 * Validates the schema, parses argv, prints help or errors, runs completion or the leaf handler, then exits.
 *
 * @param root The root CliCommand.
 * @param argv Override the default argv (process.argv.slice(2)).
 */
export declare function cliRun(root: CliCommand, argv?: string[]): Promise<never>;
/**
 * Prints a red error line and contextual help on stderr, then exits with status 1.
 */
export declare function cliErrWithHelp(ctx: CliContext, msg: string): never;
/** True when stdin is a TTY. */
export declare const isInteractiveTty: boolean;

export {};
