// Generated by dts-bundle-generator v9.5.1

export type ResolvedConfig = Record<string, unknown>;
declare class EmptyAppConfigSnapshot {
	get(_key: string): undefined;
	require(key: string): never;
	set(_key: string, _value: unknown): void;
	read(): ResolvedConfig;
}
declare class AppConfigSnapshot {
	private readonly program;
	private snapshot;
	private fileData;
	constructor(program: CliProgram, fileData: Record<string, unknown>, resolved: ResolvedConfig);
	get(key: string): unknown;
	require(key: string): unknown;
	set(key: string, value: unknown): void;
	read(): ResolvedConfig;
	/** Replace snapshot after external bootstrap (internal). */
	refresh(fileData: Record<string, unknown>, resolved: ResolvedConfig): void;
	private assertEntryKey;
}
export type AnyAppConfigSnapshot = AppConfigSnapshot | EmptyAppConfigSnapshot;
/** Coerced leaf inputs keyed by option and positional names. */
export type CliLeafInputs = Record<string, boolean | number | string | string[] | undefined>;
/**
 * Values passed to a leaf command handler after parsing: app name, routed path, args, and merged options.
 */
export declare class CliContext {
	readonly appName: string;
	readonly commandPath: string[];
	readonly args: string[];
	readonly program: CliProgram;
	readonly opts: Record<string, string>;
	readonly invocation: CliInvocation;
	readonly appConfig: AnyAppConfigSnapshot;
	/** Captures the program root, routed path, positional words, and option map for a leaf handler. */
	constructor(appName: string, commandPath: string[], args: string[], opts: Record<string, string>, program: CliProgram, invocation?: CliInvocation, appConfig?: AnyAppConfigSnapshot);
	/** Returns whether a presence flag was set (including implicit "1" for boolean options). */
	hasFlag(name: string): boolean;
	/** Returns the string value for a string-valued option, if present. */
	stringOpt(name: string): string | undefined;
	/** Parses a stored string as a number; returns null if missing or not a strict double string. */
	numberOpt(name: string): number | null;
	/**
	 * Generic typed accessor: parses a stored string using the provided parse function.
	 * This is the TypeScript-native advantage over the Swift version.
	 */
	typedOpt<T>(name: string, parse: (s: string) => T): T | null;
	/** Duration option in milliseconds (post-parse validated). */
	durationOpt(name: string): number | undefined;
	/** Comma-list option as a string array (post-parse validated). */
	commaListOpt(name: string): string[] | undefined;
	/** Date option as canonical YYYY-MM-DD (post-parse validated). */
	dateOpt(name: string): string | undefined;
	/** Date-time option as normalized ISO 8601 UTC (post-parse validated). */
	dateTimeOpt(name: string): string | undefined;
	/** Returns the value(s) for a named positional slot. Varargs slots return string[]; single slots return string | undefined. */
	positional(name: string): string | string[] | undefined;
	/** Reads coerced option and positional values for the current leaf from schema metadata. */
	readLeafInputs(): CliLeafInputs;
	private _readOptionValue;
	private _leafNode;
	private _posMap;
	private _positionalMap;
}
/**
 * How a leaf handler was dispatched.
 */
export type CliInvocation = "cli" | "mcp";
/**
 * Option kinds: presence (boolean flag), string (free-form text), number (strict double), or enum (fixed choices).
 */
export declare enum CliOptionKind {
	/** Boolean flag: no value token (may be implicit `"1"` when set). */
	Presence = "presence",
	/** Free-form string value. */
	String = "string",
	/** Strict floating-point value (parsed at validation time). */
	Number = "number",
	/** Fixed set of allowed string values. Requires non-empty `choices` on the option. */
	Enum = "enum"
}
/**
 * Named validation/coercion for string options (`format` on `CliOption`).
 * Positionals do not use `format`; varargs use space-separated CLI tokens and JSON arrays over MCP.
 */
export declare enum CliValueFormat {
	/** Duration text such as `30s`, `20m`, `1h`, `2d` (default unit minutes when omitted). */
	Duration = "duration",
	/** Comma-separated list on a single option value (`--services a,b`). */
	CommaList = "comma-list",
	/** Calendar date `YYYY-MM-DD`. */
	Date = "date",
	/** RFC 3339 instant with `Z` or numeric offset. */
	DateTime = "date-time"
}
/**
 * When `fallbackCommand` is used for missing or unknown subcommand tokens at a routing node.
 */
export declare enum CliFallbackMode {
	/**
	 * If argv has no next subcommand, route to `fallbackCommand`; if the token is unknown, error.
	 */
	MissingOnly = "missingOnly",
	/**
	 * If argv has no next subcommand or the token is not a known child, route to `fallbackCommand`.
	 */
	MissingOrUnknown = "missingOrUnknown",
	/**
	 * If the next token is present but not a known child, route to `fallbackCommand`.
	 * When the subcommand token is missing (exhausted argv), do not use fallback (implicit scoped help).
	 */
	UnknownOnly = "unknownOnly"
}
/**
 * A named flag or value option (`--long`, `-short`), listed on command `options`.
 */
export interface CliOption {
	/** Option name (e.g., "name", "verbose"). */
	name: string;
	/** When `true`, omit from help, schema, completions, and MCP tool inputSchema (still parseable). */
	hidden?: boolean;
	/** Description shown in help. */
	description: string;
	/** Option kind: presence flag, string value, or number value. */
	kind: CliOptionKind;
	/** Short option character (e.g., 'n' for -n). */
	shortName?: string;
	/** Whether this option must be provided. Cannot be used with Presence kind. */
	required?: boolean;
	/**
	 * Allowed values. Required when kind === Enum; ignored otherwise.
	 * Must be a non-empty array of distinct non-empty strings.
	 */
	choices?: string[];
	/**
	 * Named string validation for `kind: String` options. Mutually exclusive with `pattern`.
	 * Not supported on positionals.
	 */
	format?: CliValueFormat;
	/** Default value applied in post-parse when the option is omitted. */
	default?: string;
	/** Regex pattern for string options. Mutually exclusive with `format`. */
	pattern?: string;
}
/**
 * An ordered positional argument slot, listed on leaf `positionals`.
 */
export interface CliPositional {
	/** Positional name (used in help and error messages). */
	name: string;
	/** Description shown in help. */
	description: string;
	/** Value kind for each consumed token. */
	kind: CliOptionKind;
	/**
	 * Minimum number of values required (default 1).
	 * Use `0` for an optional slot when paired with `argMax: 1`, or a varargs tail with `argMax: 0`.
	 */
	argMin?: number;
	/**
	 * Maximum number of values (`1` = a single required or optional word; default 1). Use `0` for an
	 * unbounded varargs tail (must be the last slot in the command’s `positionals` list).
	 */
	argMax?: number;
}
/** Optional metadata for `mcp bundle` MCP Bundle output (program root `mcpServer.bundle` only). */
export interface CliMcpBundleConfig {
	author?: {
		name: string;
		email?: string;
		url?: string;
	};
	/** Repo-relative path to a PNG icon copied into the bundle. */
	icon?: string;
	/** Manifest `long_description` (defaults to program description). */
	longDescription?: string;
}
/**
 * Enables `myapp mcp` and MCP stdio server metadata (program root only).
 * Must include `enabled: true`; omit `mcpServer` entirely to disable MCP.
 */
export interface CliMcpServerConfig {
	/** When `true`, enables the `mcp` built-in and MCP stdio server. */
	enabled: boolean;
	/** Resource URI for schema export (default: `<sanitized root key>://schema`). */
	schemaResourceUri?: string;
	/**
	 * Capture the user's login shell environment at MCP server start and merge it
	 * into process.env. Solves missing PATH, nvm/rbenv shims, Homebrew binaries,
	 * and shell exports that MCP hosts (e.g. Cursor) don't inherit.
	 */
	shellEnv?: boolean | string;
	/**
	 * Custom MCP resources exposed alongside the built-in schema resource.
	 * URIs must be unique and must not equal schemaResourceUri.
	 */
	resources?: CliMcpResource[];
	/** Optional MCP Bundle (`.mcpb`) metadata for `mcp bundle`. */
	bundle?: CliMcpBundleConfig;
}
/**
 * A custom MCP resource exposed under resources/list and resources/read.
 */
export interface CliMcpResource {
	/** Resource URI (must be unique; must not equal schemaResourceUri). */
	uri: string;
	/** Short display name for resources/list. */
	name: string;
	/** Optional human description for resources/list. */
	description?: string;
	/** MIME type (default: "text/plain"). */
	mimeType?: string;
	/** Called at resources/read time; must return the resource body. */
	load: () => string;
}
/**
 * Leaf-only. Controls how this command appears as an MCP tool.
 */
export interface CliMcpToolConfig {
	/** When `false`, omit from `tools/list` (default: exposed). */
	enabled?: boolean;
	/**
	 * Override the generated MCP tool description.
	 * Default: auto-generated from command path and description.
	 */
	description?: string;
	/**
	 * @deprecated Set `outputSchema` on the leaf command instead.
	 */
	outputSchema?: Record<string, unknown>;
}
/**
 * Opt-out and defaults for the `install` built-in (program root only).
 */
export interface CliUpdateArtifact {
	/** Path to an executable binary to copy into the install location. */
	path: string;
	/** Release version of `path` (used for already-current checks and success messages). */
	version?: string;
	/** Called after reinstall completes (e.g. remove a temp download directory). */
	cleanup?: () => void | Promise<void>;
}
/** Fetches the latest release binary for `install --update`. */
export type CliUpdateGetLatest = (ctx: {
	version: string;
}) => Promise<CliUpdateArtifact>;
/**
 * Metadata overlay for one key in {@link CliAppConfig.entries}.
 * Types and validation come from {@link CliAppConfig.jsonSchema} when set; otherwise all values are strings.
 */
export interface CliAppConfigEntry {
	/** Help text for prompts, MCP manifests, and generated docs. */
	description: string;
	/** Short label in host UIs and CLI prompts. Default: the config key. */
	title?: string;
	/** Default when `jsonSchema` is omitted (all-string mode). */
	default?: string;
	/** When `false`, optional for bootstrap and MCP enforcement. Default: `true`. */
	required?: boolean;
	/**
	 * Mask stdin during prompts and redact on `config get`.
	 * Default: `/key|token|secret|password/i.test(name)`.
	 */
	sensitive?: boolean;
	/** When set: non-empty `process.env[env]` overrides file; value exported after resolve. */
	env?: string;
}
/**
 * App configuration block on the program root ({@link CliProgram.appConfig}).
 */
export interface CliAppConfig {
	/** Default: `~/.config/<sanitized-key>/config` (or `%APPDATA%/<key>/config` on Windows). */
	path?: string;
	/** Built-in `config get` / `config set`. Default: enabled when `appConfig` is set. */
	commands?: boolean | {
		enabled?: boolean;
		mcpSet?: boolean;
	};
	/** Block JSON Schema (draft-07). When omitted, synthesize all-string schema from `entries`. */
	jsonSchema?: Record<string, unknown>;
	/** Per-key metadata; keys must match `jsonSchema.properties` when `jsonSchema` is set. */
	entries: Record<string, CliAppConfigEntry>;
}
export interface CliInstallConfig {
	/** When `false`, hide/disable `install` (default: enabled). */
	enabled?: boolean;
	/** Default bin directory (default: `~/.local/bin`). Overridden by `INSTALL_PREFIX` env and `--prefix`. */
	prefix?: string;
	/**
	 * When set, enables `install --update` on the program root.
	 * Should download or locate the latest release binary and return its path.
	 */
	updateGetLatest?: CliUpdateGetLatest;
}
/**
 * One bundled documentation topic for the `docs` built-in (program root only).
 */
export interface CliDocsTopic {
	/** Bundled markdown (use compile-time text imports in the consumer). */
	text: string;
	/** Leaf help text for `myapp docs <key> -h`. Auto-generated from key when omitted. */
	description?: string;
}
/**
 * Enables `myapp docs` and bundled markdown topics (program root only).
 * Must include `enabled: true`; omit `docs` entirely to disable.
 */
export interface CliDocsConfig {
	/** When `true`, enables the `docs` built-in command group. */
	enabled: boolean;
	/** Router description for `myapp docs` (default: "Print bundled CLI documentation."). */
	description?: string;
	/**
	 * Subcommand for bare `myapp docs` (maps to router `fallbackCommand`).
	 * When omitted, uses the first key in `topics` (insertion order).
	 */
	defaultTopic?: string;
	/** Topic key → bundled markdown. Reserved keys: `mcp`, `all` (supplied by the built-in). */
	topics: Record<string, CliDocsTopic>;
}
/**
 * Base properties shared by all nodes in the user command tree.
 */
export interface CliNodeBase {
	/** Program or command key (e.g., "myapp", "stat", "owner"). */
	key: string;
	/** When `true`, omit from help listings, schema, completions, and MCP tools (still invocable). */
	hidden?: boolean;
	/** Short description shown in help. */
	description: string;
	/** Additional notes shown in help (`{argsbarg:program}` → program key). */
	notes?: string;
	/** Global or command-level flags/options. */
	options?: CliOption[];
}
/**
 * A leaf command node with a handler and optional positionals.
 */
export type CliLeaf = CliNodeBase & {
	/** Handler function for leaf commands. */
	handler: CliHandler;
	/** Positional argument definitions. */
	positionals?: CliPositional[];
	/**
	 * JSON Schema for structured stdout (e.g. with `--json` or MCP when the handler emits JSON).
	 * Exported in `docs schema`, `docs api`, and MCP `tools/list`; not validated at runtime yet.
	 */
	outputSchema?: Record<string, unknown>;
	/** Per-tool MCP exposure and metadata. */
	mcpTool?: CliMcpToolConfig;
};
/**
 * A routing command node with nested subcommands.
 */
export type CliRouter = CliNodeBase & {
	/** Nested subcommands. */
	commands: CliNode[];
	/** Default subcommand when argv omits a command or uses an unknown token at this routing node. */
	fallbackCommand?: string;
	/** How fallbackCommand is applied at this routing node. */
	fallbackMode?: CliFallbackMode;
};
/**
 * A node in the user-defined command tree (router or leaf).
 */
export type CliNode = CliLeaf | CliRouter;
/**
 * Program root passed to {@link Cli}.
 * May be a leaf or router, plus optional program-level MCP and install config.
 */
export type CliProgram = CliNode & {
	/** Program version (printed by the `version` built-in and MCP serverInfo). */
	version: string;
	/** Schema-driven app config file, bootstrap, and MCP metadata. */
	appConfig?: CliAppConfig;
	/** When set with `enabled: true`, enables the `mcp` built-in subcommand. */
	mcpServer?: CliMcpServerConfig;
	/** Opt-out and defaults for `install`. */
	install?: CliInstallConfig;
	/** When set with `enabled: true`, enables the `docs` built-in command group. */
	docs?: CliDocsConfig;
};
/**
 * Handler closure type for leaf commands.
 * Supports both sync and async handlers.
 */
export type CliHandler = (ctx: CliContext) => void | Promise<void>;
/**
 * Error thrown when the static CLI tree violates ArgsBarg rules.
 */
export declare class CliSchemaValidationError extends Error {
	/** Creates a schema validation error with a human-readable rule violation. */
	constructor(message: string);
}
/** Platform builtins derived from program config and runtime. */
export interface CliCapabilities {
	completion: true;
	mcp: boolean;
	install: boolean;
	docs: boolean;
	update: boolean;
	configCommands: boolean;
}
/** JSON-safe command node (no handlers). */
export interface CliSchemaExport {
	key: string;
	description: string;
	notes?: string;
	/** JSON Schema for structured stdout when set on the leaf. */
	outputSchema?: Record<string, unknown>;
	options?: CliOption[];
	fallbackCommand?: string;
	fallbackMode?: CliFallbackMode;
	commands?: CliSchemaExport[];
	positionals?: CliPositional[];
}
/** Outcome of a non-exiting CLI invocation. */
export type CliInvokeKind = "ok" | "help" | "error";
/** Result of Cli.invoke: captured output and exit metadata without process.exit. */
export interface CliInvokeResult {
	kind: CliInvokeKind;
	exitCode: number;
	stdout: string;
	stderr: string;
	errorMsg?: string;
}
/** Argsbarg runtime for a validated, frozen {@link CliProgram}. */
export declare class Cli {
	readonly program: CliProgram;
	readonly caps: CliCapabilities;
	private readonly parseRootMerged;
	private readonly presentationRoot;
	private _appConfig?;
	constructor(program: CliProgram);
	get appConfig(): AnyAppConfigSnapshot;
	exportCommandSchema(): CliSchemaExport;
	exportAppConfigSchema(): Record<string, unknown> | undefined;
	run(argv?: string[]): Promise<never>;
	invoke(argv: string[]): Promise<CliInvokeResult>;
	serveMcp(): Promise<never>;
	private prepareDispatch;
	private buildAppConfigSnapshot;
}
export declare function cliErrWithHelp(ctx: CliContext, msg: string): never;
/** Parses a duration string (e.g. 20m, 1h, 30s) into milliseconds. */
export declare function parseDurationMs(durationStr: string): number;
/** Splits a comma-separated string into trimmed non-empty tokens. */
export declare function parseCommaList(s: string): string[];
/** Returns canonical YYYY-MM-DD after validation. */
export declare function parseDate(s: string): string;
/** Returns normalized ISO 8601 UTC after validation. */
export declare function parseDateTime(s: string): string;
/** Minimal context for headless routing helpers. */
export type HeadlessContext = Pick<CliContext, "invocation">;
/** True when `--json` was passed or the handler was invoked via MCP. */
export declare function wantsExplicitJson(ctx: HeadlessContext, hasJsonFlag: boolean): boolean;
/**
 * Headless when MCP, `--json`, `--dry-run`, or stdin is not a TTY.
 * Use for commands that should auto-emit JSON in pipelines.
 */
export declare function shouldRunHeadless(ctx: HeadlessContext, hasJsonFlag: boolean, hasDryRunFlag?: boolean, interactive?: boolean): boolean;
/**
 * Like {@link shouldRunHeadless}, but only auto-headless in non-TTY when positionals are present.
 * Avoids turning empty invocations into JSON errors.
 */
export declare function shouldRunHeadlessWithPositionals(ctx: HeadlessContext, hasJsonFlag: boolean, positionals: string[], hasDryRunFlag?: boolean, interactive?: boolean): boolean;
/**
 * Headless when MCP, `--dry-run` with required args, or non-TTY with `--yes` and required args.
 * Use for mutating commands that require explicit `--yes` in scripts.
 */
export declare function shouldRunHeadlessWithYes(ctx: HeadlessContext, opts: {
	yes: boolean;
	hasRequiredArgs: boolean;
	dryRun?: boolean;
}, interactive?: boolean): boolean;
/**
 * Exits when non-interactive mode is used without `--yes`.
 * @param hint - Command-specific guidance appended to the error
 */
export declare function requireYesInNonTty(yes: boolean, hint: string, dryRun?: boolean, interactive?: boolean): void;
/** Prefixes a success message when running in dry-run mode. */
export declare function formatDryRunMessage(message: string, dryRun: boolean): string;
/** Config for {@link ghReleaseUpdateGetLatest}. */
export interface GhReleaseUpdateConfig {
	/** GitHub `owner/repo` slug. */
	repo: string;
	/** Release asset filename (e.g. `myapp`). */
	asset: string;
	/** Temp directory name prefix for downloads. */
	tempPrefix: string;
	/** Path to the on-disk version-check cache JSON file. */
	cachePath: string;
	/** Optional hint when `gh auth` fails or no releases exist. */
	repoEnvHint?: string;
}
/** Config for {@link createGhVersionCheck}. */
export interface GhVersionCheckConfig {
	/** Installed semver string. */
	currentVersion: string;
	/** CLI command name for update notices (e.g. `qa`). */
	commandName: string;
	/** Path to the on-disk version-check cache JSON file. */
	cachePath: string;
	/** Cache TTL in milliseconds (default 24h). */
	ttlMs?: number;
	/** When true, skip background refresh (e.g. test subprocess). */
	skipRefresh?: () => boolean;
	/** When true, skip refresh because `gh` is unavailable. */
	ghAvailable?: () => boolean;
	/** Fetches latest release version via `gh`. */
	fetchLatest: () => Promise<string>;
}
/** Returns whether the installed version matches the latest release. */
export declare function isAlreadyCurrent(current: string, latest: string): boolean;
/** Strips a leading `v` from a release tag. */
export declare function parseReleaseTag(tag: string): string;
/** Builds a `CliUpdateGetLatest` hook that downloads a release via `gh`. */
export declare function ghReleaseUpdateGetLatest(config: GhReleaseUpdateConfig): CliUpdateGetLatest;
/** Version-check cache helpers for summary notices and background refresh. */
export declare function createGhVersionCheck(config: GhVersionCheckConfig): {
	getUpdateNotice: () => string | null;
	refreshIfStale: () => void;
};
/** Shared `gh release view` fetcher for hooks and version-check refresh. */
export declare function createGhFetchLatest(config: Pick<GhReleaseUpdateConfig, "repo" | "repoEnvHint">): () => Promise<string>;
/** Resolved paths for `mcp bundle`. */
export interface McpBundlePaths {
	binaryPath: string;
	outPath: string;
	binaryName: string;
}
/** Default `dist/<key>` binary and `dist/<key>.mcpb` output under cwd. */
export declare function defaultMcpBundlePaths(program: CliProgram, cwd?: string): McpBundlePaths;
/** Generates MCPB `manifest.json` object from program schema and MCP tools. */
export declare function generateMcpManifest(program: CliProgram, binaryName: string): Record<string, unknown>;
export interface PackMcpBundleOpts {
	cwd?: string;
	binaryPath?: string;
	outPath?: string;
}
/**
 * Stages manifest + binary (+ optional icon) and writes a `.mcpb` ZIP.
 * Requires the compiled binary to exist.
 */
export declare function packMcpBundle(program: CliProgram, opts?: PackMcpBundleOpts): string;
/** True when stdin is a TTY. */
export declare const isInteractiveTty: boolean;

export {};
