/*
Generate JSON Schema artifacts and bridge modules from discovered types.ts roots.
*/

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { createGenerator } from "ts-json-schema-generator";
import { discoverSchemaRoots, type SchemaRoot } from "./schemagen/discover-schema-roots.ts";
import { jsonImportVar } from "./schemagen/naming.ts";

const projectRoot = join(import.meta.dir, "..");
const generatedDir = join(projectRoot, "schemas", "generated");

function generateJson(root: SchemaRoot): Record<string, unknown> {
  const generator = createGenerator({
    path: join(projectRoot, root.relFile),
    type: root.typeName,
    tsconfig: join(projectRoot, "tsconfig.json"),
    topRef: false,
    skipTypeCheck: false,
    jsDoc: "extended",
    additionalProperties: root.kind === "config" ? false : undefined,
  });
  const schema = generator.createSchema(root.typeName) as Record<string, unknown>;
  if (root.kind === "config") {
    schema.additionalProperties = false;
  }
  return schema;
}

function writeBridge(path: string, scriptName: string, roots: SchemaRoot[], banner: string): void {
  const lines = [`// Auto-generated by scripts/${scriptName} — do not edit by hand.`, ""];
  for (const root of roots) {
    const varName = jsonImportVar(root.outfile);
    lines.push(`import ${varName} from "./generated/${root.outfile}";`);
  }
  if (roots.length > 0) {
    lines.push("");
  }
  for (const root of roots) {
    const varName = jsonImportVar(root.outfile);
    lines.push(`/** ${banner} \`${root.typeName}\`. */`);
    lines.push(`export const ${root.exportName} = ${varName} as Record<string, unknown>;`);
    lines.push("");
  }
  writeFileSync(path, `${lines.join("\n")}`);
}

const roots = discoverSchemaRoots(projectRoot);
const configRoots = roots.filter((r) => r.kind === "config");
const outputRoots = roots.filter((r) => r.kind === "output");

mkdirSync(generatedDir, { recursive: true });

for (const root of roots) {
  const schema = generateJson(root);
  const outPath = join(generatedDir, root.outfile);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, `${JSON.stringify(schema, null, 2)}\n`);
  console.log(`wrote schemas/generated/${root.outfile} (${root.typeName})`);
}

writeBridge(
  join(projectRoot, "schemas", "configSchemas.ts"),
  "schemagen.ts",
  configRoots,
  "JSON Schema for program.appConfig.jsonSchema from",
);
writeBridge(
  join(projectRoot, "schemas", "outputSchemas.ts"),
  "schemagen.ts",
  outputRoots,
  "JSON Schema for leaf outputSchema from",
);

console.log(`config roots: ${configRoots.length}, output roots: ${outputRoots.length}`);
