// Auto-generated by scripts/schemagen.ts — do not edit by hand.

import app_config from "./generated/app-config.json";

/** JSON Schema for program.appConfig.jsonSchema from `AppConfig`. */
export const APP_CONFIG_JSON_SCHEMA = app_config as Record<string, unknown>;
