// Auto-generated by scripts/schemagen.ts — do not edit by hand.

import status from "./generated/status.json";

/** JSON Schema for leaf outputSchema from `StatusJsonOutput`. */
export const STATUS_JSON_OUTPUT_SCHEMA = status as Record<string, unknown>;
