/*
Generate JSON Schema artifacts under __generated__/ and write index.ts re-exports.
*/

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { createGenerator } from "ts-json-schema-generator";
import { cleanStaleGenerated } from "./cleanup.ts";
import { discoverSchemaRoots, type SchemaRoot, type SchemaRootKind } from "./discover-schema-roots.ts";
import { GENERATED_DIR, schemaExportName, schemaJsonBasename, schemaJsonImportVar } from "./names.ts";

const KIND_ORDER: SchemaRootKind[] = ["config", "input", "output"];

export interface RunSchemagenOptions {
  /** Project root (default: `process.cwd()`). */
  projectRoot?: string;
  /** Source tree directory relative to project root (default: `src`). */
  srcDir?: string;
  /** Path to tsconfig relative to project root (default: `tsconfig.json`). */
  tsconfig?: string;
}

export interface RunSchemagenResult {
  configRoots: number;
  inputRoots: number;
  outputRoots: number;
}

function resolveTsconfig(projectRoot: string, tsconfig: string): string {
  const path = join(projectRoot, tsconfig);
  try {
    return path;
  } catch {
    throw new Error(`tsconfig not found: ${path}`);
  }
}

function generateJson(projectRoot: string, tsconfigPath: string, root: SchemaRoot): Record<string, unknown> {
  const generator = createGenerator({
    path: join(projectRoot, root.path),
    type: root.typeName,
    tsconfig: tsconfigPath,
    topRef: false,
    skipTypeCheck: false,
    jsDoc: "extended",
    additionalProperties: root.kind === "config" ? false : undefined,
  });
  const schema = generator.createSchema(root.typeName) as Record<string, unknown>;
  if (root.kind === "config") {
    schema.additionalProperties = false;
  }
  return schema;
}

function writeGeneratedIndex(generatedDir: string, roots: SchemaRoot[]): void {
  const sorted = [...roots].sort((left, right) => KIND_ORDER.indexOf(left.kind) - KIND_ORDER.indexOf(right.kind));
  const lines = ["// Auto-generated by argsbarg schemagen — do not edit by hand.", ""];
  for (const root of sorted) {
    lines.push(`import ${schemaJsonImportVar(root.kind)} from "./${schemaJsonBasename(root.kind)}";`);
  }
  if (sorted.length > 0) {
    lines.push("");
  }
  for (const root of sorted) {
    lines.push(
      `export const ${schemaExportName(root.kind)} = ${schemaJsonImportVar(root.kind)} as Record<string, unknown>;`,
    );
    lines.push("");
  }
  writeFileSync(join(generatedDir, "index.ts"), `${lines.join("\n")}`);
}

/** Generate colocated `__generated__` JSON schemas and `index.ts` barrels. */
export function runSchemagen(options: RunSchemagenOptions = {}): RunSchemagenResult {
  const projectRoot = options.projectRoot ?? process.cwd();
  const srcDir = options.srcDir ?? "src";
  const tsconfigPath = resolveTsconfig(projectRoot, options.tsconfig ?? "tsconfig.json");

  const roots = discoverSchemaRoots(projectRoot, srcDir);
  const bySchemaFile = new Map<string, SchemaRoot[]>();

  for (const root of roots) {
    const schema = generateJson(projectRoot, tsconfigPath, root);
    const generatedDir = join(dirname(join(projectRoot, root.path)), GENERATED_DIR);
    mkdirSync(generatedDir, { recursive: true });
    const jsonPath = join(generatedDir, schemaJsonBasename(root.kind));
    writeFileSync(jsonPath, `${JSON.stringify(schema, null, 2)}\n`);
    console.log(`wrote ${relative(projectRoot, jsonPath)} (${root.typeName})`);

    const list = bySchemaFile.get(root.path) ?? [];
    list.push(root);
    bySchemaFile.set(root.path, list);
  }

  for (const [relPath, fileRoots] of bySchemaFile) {
    const generatedDir = join(dirname(join(projectRoot, relPath)), GENERATED_DIR);
    writeGeneratedIndex(generatedDir, fileRoots);
    console.log(`wrote ${relative(projectRoot, join(generatedDir, "index.ts"))}`);
  }

  cleanStaleGenerated(projectRoot, srcDir, bySchemaFile);

  return {
    configRoots: roots.filter((r) => r.kind === "config").length,
    inputRoots: roots.filter((r) => r.kind === "input").length,
    outputRoots: roots.filter((r) => r.kind === "output").length,
  };
}
